In [1]:
import helpers
import numpy as np

In [2]:
envs = helpers.create_envs()
agents = helpers.create_agents(envs[0])

In [3]:
a = helpers.action_step(agents, envs, [env.reset() for env in envs])

In [6]:
a[1]

({0: -0.0, 1: 0.05713217},
 {0: 0.059943072, 1: 0.040315416},
 {0: 0.040453166, 1: 0.04469134},
 {0: -0.0, 1: 0.060803205},
 {0: 0.03420105, 1: 0.05320229})

In [6]:
a = dict(enumerate(range(5)))
a

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4}

In [8]:
a.transpose(1, 0, 2).shape

(5, 2, 140)

In [17]:
p = agents[0].make_decisions(states)

In [18]:
p

[array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32)]