In [12]:
import helpers
import numpy as np
import scipy.stats as stats

In [8]:
a = np.ones((21, 3)) + [0, 1, 2]

In [9]:
a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [2]:
envs = helpers.create_envs(yamls_filename='yamls/2_region_yamls')[0]
# agents = helpers.create_agents(envs[0])

In [6]:
a = helpers.get_baseline_cum_returns(envs, n_trials=1_000)

100%|███████████████████████████████████████████████████████████████████████████| 1000/1000 [00:19<00:00, 51.88it/s]


In [20]:
stats.boxcox(a)[1]

2.987852611501489

In [19]:
stats.boxcox(a)[0].std()

59.04233714080136

In [17]:
stats.shapiro(stats.boxcox(a)[0])

ShapiroResult(statistic=0.9988633394241333, pvalue=0.7951122522354126)

In [19]:
envs[0].reset()
envs[0].global_state['reward_all_regions']['value'].shape

(21, 2)

In [3]:
r = envs[0].estimate_reward_distribution()

100%|███████████████████████████████████████| 1000/1000 [00:37<00:00, 26.35it/s]


In [4]:
r.mean(0)

array([0.11810149, 0.11719461, 0.11682205, 0.11741002], dtype=float32)

In [4]:
r.mean(0)

array([0.1837245, 0.1839157], dtype=float32)

In [12]:
r.mean(0)

array([0.12683399, 0.05198448, 0.03085149, 0.07488997, 0.02121781,
       0.2828288 , 0.01516363, 0.02213184, 0.22927459, 0.03168111,
       0.07750511, 0.08832972, 0.25673124, 0.14492033, 0.07246767,
       0.9541912 , 0.5645132 , 0.23426142, 0.27817056, 0.11703864,
       0.66655827, 0.08648663, 0.26146117, 0.03011092, 0.20305464,
       0.05462708, 0.21177474], dtype=float32)

In [3]:
states = [env.reset() for env in envs]

In [4]:
new_states = helpers.proposals_step(agents, envs, states)

In [5]:
new_new_states = helpers.decisions_step(agents, envs, new_states)

In [6]:
s, r = helpers.action_step(agents, envs, new_new_states)

In [7]:
r

({0: 0.05888777, 1: 0.026819868, 2: 0.14720672, 3: 0.16434895},
 {0: 0.280478, 1: 0.02202305, 2: 0.12687464, 3: 0.16556157},
 {0: 0.0023812728, 1: 0.013697322, 2: 0.21270674, 3: 0.0061370214},
 {0: 0.1854819, 1: 0.054339632, 2: 0.265243, 3: 0.10809251},
 {0: 0.08262519, 1: 0.016553843, 2: 0.31943807, 3: 0.20569865})