In [2]:
!python --version

Python 3.7.16


In [1]:
import os
os.chdir("..")
from rice import Rice

from tqdm import tqdm

import helper_scripts
from PPO_negotiation import PPO

In [2]:
env = Rice(region_yamls_filename='fewer_region_yamls/')

In [3]:
initial_state = env.reset()

In [4]:
agent = PPO(state_dim = len(initial_state[0]['features']), 
            action_dim = env.action_space[0],
            params = helper_scripts.default_params,
            device = 'cpu')

In [7]:
agent.select_action(initial_state[0])

State shape: torch.Size([1, 77]), Mask shape: torch.Size([1, 11, 10])
Logits shape: torch.Size([1, 64])
Action Logits shape : 11 x torch.Size([1, 10])
[tensor([[-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,  7.4348e-02]]), tensor([[-0.0606,  0.0607, -0.0870, -0.0276,  0.0041,  0.0169,  0.0061, -0.0234,
         -0.1522,  0.0085]]), tensor([[-0.0018, -0.2074, -0.1147, -0.1046, -0.0275, -0.0311, -0.0181, -0.1058,
         -0.0795,  0.1120]]), tensor([[ 0.0758,  0.0763, -0.0003, -0.0842,  0.1485,  0.1548, -0.1344,  0.0363,
         -0.0486,  0.0490]]), tensor([[-0.0063,  0.1054, -0.0831,  0.0322, -0.1535,  0.0467,  0.0477, -0.1612,
         -0.0800,  0.0083]]), tensor([[ 0.0747,  0.0363, -0.0448,  0.0016,  0.0824, -0.0420, -0.0548,  0.0221,
          0.0031,  0.1323]]), tensor([[ 0.0371, -0.0122, -0.0555,  0.0498, -0.0156,  0.0342,  0.1342,  0.0148,
          0.0859, -0.1588]]), tensor([[ 0.1595,  0.0181, -0.0

[array([9, 5, 5, 4, 2, 1, 5, 0, 3, 5, 1])]

In [6]:
agent.action_mask[0][0] = False
agent.action_mask

tensor([[0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)

In [6]:
env.agent_action_masks[0][0][0:9] = 0
env.agent_action_masks[0]

array([[False, False, False, False, False, False, False, False, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [13]:
a = env.agent_action_masks[0]
a.shape

(11, 10)

In [14]:
a[:, 0]

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])